version: 2

build:
  os: ubuntu-24.04
  tools:
    # NB As of 2026-03-16, Python 3.14 cannot be used because
    # all versions of pyam-iamc since v1.3.1 (2022-02-04) set
    # upper bounds on Python; and this version requires an
    # outdated pint <= 0.17.
    python: "3.13"

python:
  install:
  - method: pip
    path: .
    extra_requirements: [docs,tests]

sphinx:
  configuration: doc/conf.py
