version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    post_install:
    - pip install "plotnine != 0.13.0"

python:
  install:
  - method: pip
    path: .
    extra_requirements: [docs,tests]
